add support for the Microsoft simulator format (#35)
"mssim" is a transmission interface for the Microsoft simulator, which
is supported by TPM utilities such as tpm2-tool[1]. This RPC format
also goes by "socsim"[2].

The format was donated by Microsoft to the TPM2 specification, and is
primarily implemented by a simulator maintained by IBM[3]. This PR allows
go-tpm to interact with that simulator, and lets users run examples
without access to a real TPM2 device.

To run the tests, compile and run tpm_server[4].

```
$ tpm_server
TPM command server listening on port 2321
Platform server listening on port 2322
```

Then execute the following command. This PR currently passes many of the
integration tests, but fails on the following (I've not looked into why
yet):

```
$ go test github.com/google/go-tpm/tpm2 -args -mssim
--- FAIL: TestCombinedKeyTest (0.20s)
    tpm2_test.go:136: CreateKey failed: response status 0x921
--- FAIL: TestCombinedEndorsementTest (0.21s)
    tpm2_test.go:162: CreateKey failed: response status 0x921
--- FAIL: TestCombinedContextTest (0.26s)
    tpm2_test.go:205: CreateKey failed: response status 0x921
--- FAIL: TestEvictControl (0.29s)
    tpm2_test.go:239: CreateKey failed: response status 0x921
--- FAIL: TestCertify (0.31s)
    tpm2_test.go:375: Certify failed: response status 0x921
--- FAIL: TestCertifyExternalKey (0.79s)
    --- FAIL: TestCertifyExternalKey/RSA (0.50s)
        tpm2_test.go:479: Certify failed: response status 0x921
    --- FAIL: TestCertifyExternalKey/ECC (0.13s)
        tpm2_test.go:503: Certify failed: response status 0x921
--- FAIL: TestSign (0.33s)
    --- FAIL: TestSign/RSA (0.18s)
        tpm2_test.go:529: Sign failed: response status 0x921
    --- FAIL: TestSign/ECC (0.14s)
        tpm2_test.go:529: Sign failed: response status 0x921
--- FAIL: TestReadPCR (0.04s)
    tpm2_test.go:590: PCR 16 value missing from response
FAIL
FAIL    github.com/google/go-tpm/tpm2   3.332s
```

[1] https://github.com/tpm2-software/tpm2-tools/blob/master/man/common/tcti.md
[2] https://blog.hansenpartnership.com/tpm2-and-linux/
[3] https://sourceforge.net/projects/ibmswtpm2/
[4] https://github.com/tpm2-software/tpm2-tools/blob/master/INSTALL.md#tpm-simulator